- README.md
Hey, so this is just a tiny fix for the readme. It seems that markdown acts in some weird ways when indenting stuff haha
> fix(readme): correct code block for nvim-cmp example

- lua/neogen/configurations/c.lua
Hi,
Thanks for publishing this plugin! I wanted to use it to annotate function prototypes in C header files so I added support for this. The original functionality for the C language type should still be preserved and I've tested some edge cases locally. Will do more extensive testing tomorrow, so I'll leave this as draft for now.
> Add support for function prototype annotation

- lua/neogen/configurations/c.lua
Prior to this fix the annotation was written after the template
declaration in case the cursor did not happen to be on the same line as
the template declaration.
For example the following code
```cpp
template <typename T>
void foo(T bar); // cursor placed on this line
```
resulted in
```cpp
template <typename T>
/**
* @brief 
*
* @param bar 
*/
void foo(T bar);
```
and with this PR applied it results in
```cpp
/**
* @brief 
*
* @tparam T 
* @param bar 
*/
template <typename T>
void foo(T bar);
```
This only happened when the template declaration was on a separate line, of
course.
> Write annotation before template declarations (C++)

- README.md
- plugin/neogen.vim
This allows mapping jump functions directly without feedkeys
> add plug mappings

- lua/neogen/init.lua
If you call `setup` after `BufRead` the `configuration` table wont have been updated and you'll get an error. This calls `switch_language` at the end of `setup` to fix that.
> feat(init) switch language on setup

- lua/neogen/configurations/python.lua
In the `numpydoc` docstring style, there is supposed to be a space before the colon separating the parameter and type.[^1][^2] (even tho it looks a little weird compared to the type annotations...)
I added that missing space in this PR.
[^1]: https://numpydoc.readthedocs.io/en/latest/format.html
[^2]: https://numpydoc.readthedocs.io/en/latest/format.html
> Add space before numpydoc colon

- lua/neogen/configurations/cs.lua
I don't get parameter names without this, at least in Linux. Tested in a bare `dotnet` console app.
> fix: csharp parameters

- lua/neogen/configurations/cs.lua
- lua/neogen/templates/xmldoc.lua
This PR implements type params docs support, interface documentation and fixes issues with the xmldoc generation.
I have never seen doxygen used on a C# project, so I wonder if the default annotation type should be doxygen instead of xmldocs, but I have not changed it (for now).
> C# improvements

- lua/neogen/init.lua
- lua/neogen/snippet.lua
This pr fixes #108 
In commit c4f7e797376c8e3ab6f848bd6bc5d33019fea5e1 of LuaSnip some default options  to `ls.parser.parse_snippet`  were added.
This options when set to true (the default) perform some cleanup to the snippets by dedenting them and cleaning empty space.
Fixed the issue it by setting them to false.
Also found in the LuaSnip commit changes a reference to the function `lsp_expand` which internally calls ls.parser.parse_snippet() with this options. Maybe we should be calling that function instead?
If you could guide me to a proper solution if this isn't ok i would be glad to help.
> changed luasnip parse call options

- lua/neogen/configurations/go.lua
- lua/neogen/init.lua
- lua/neogen/templates/godoc.lua
According to https://go.dev/doc/comment, the package clause should use complete sentences. 
The `Package [package-identifier] ..." format is correct according to https://staticcheck.io/docs/checks/#ST1000
> Add godoc file template

- README.md
- doc/neogen.txt
- lua/neogen/generator.lua
- lua/neogen/init.lua
> Add annotation type autodetection

- lua/neogen/configurations/python.lua
- lua/neogen/init.lua
- lua/neogen/templates/google_docstrings.lua
Hi there! Thanks for this great extension.
This small PR fixes a few select issues I noticed with Python parameters. Please forgive any silly errors and let me know if there's anything else I can do.
Thanks!
1. **Allow `raise_statement`s like `raise Exception('Some message')` to trigger the exception raising behavior.** Instantiating an exception buries the `identifier` inside of a function call, so such `raise_statement`s aren't extracted unless recursion is allowed.
2. **Remove `self`/`cls` parameter when a function is in a class.** This functionality already existed, but the former code checked for the existence of `res.identifier` (the name of the function), which was never extracted.
3. **For `google_docstrings`: Don't include types in docstring for parameter that have a type hint.** …
> Fix parameters in python docstrings

- lua/neogen/templates/jsdoc.lua
- lua/neogen/templates/tsdoc.lua
According to the JSDoc documentation, each comment must start with a `/**` sequence.
[Use JSDoc: Getting Started with JSDoc 3](https://jsdoc.app/about-getting-started.html#adding-documentation-comments-to-your-code)
> Each comment must start with a /\*\* sequence in order to be recognized by the JSDoc parser. Comments beginning with /\*, /\*\*\*, or more than 3 stars will be ignored.
Although it is not documented, TSDoc always expects comments to start with `/**`.
[microsoft/tsdoc/tsdoc/src/parser/LineExtractor.ts](https://github.com/microsoft/tsdoc/blob/d8ce4aedcf64b5c948e7152ba02ac6c7bdedc9be/tsdoc/src/parser/LineExtractor.ts#L84)
> `'Expecting a leading "/**"'`
> JSDoc and TSDoc should always start with two asterisks

- lua/neogen/init.lua
- lua/neogen/utilities/helpers.lua
fix: https://github.com/neovim/neovim/pull/22761
> fix: Use vim.treesitter.get_node_text() to avoid deprecation warning

- lua/neogen/configurations/python.lua
- lua/neogen/init.lua
Closes: https://github.com/danymat/neogen/issues/150
Given a class with nested functions such as the one below
```python
class Thing(object):
def foo(self, bar, fizz, buzz):
def another(inner, function):
def inner_most(more, stuff):
pass
```
Where `Thing.foo` requires parameter stripping in its generated docstrings but `another` and `inner_most` are free functions whose parameters should not strip. This PR accounts for both cases. See "Before (This PR)" and "After (This PR's Fix)", below
https://github.com/danymat/neogen/assets/10103049/b1b77e43-07b3-4e8f-b7b3-d290d0f5501a
https://github.com/danymat/neogen/assets/10103049/9be32a0e-995c-4c67-aa69-97c7544bc487
I was a bit worried calling `node:parent():parent():type()` in case somehow node:parent():parent() returns nil, in which case the …
> Inner functions do not strip their first parameter

- lua/neogen/templates/google_docstrings.lua
- lua/neogen/templates/numpydoc.lua
- lua/neogen/templates/reST.lua
According to [pydocstyle rule D210](https://www.pydocstyle.org/en/6.3.0/error_codes.html) and [pep257](https://peps.python.org/pep-0257/#one-line-docstrings), there should not be any whitespace surrounding one-line docstrings. 
This PR removes those for all three python-docstring-templates
> fix: no surrounding spaces for one-line-docstring

- README.md
- docs/advanced-integration.md
- lua/neogen/generator.lua
- lua/neogen/granulator.lua
- lua/neogen/init.lua
- lua/neogen/locators/default.lua
- lua/neogen/locators/lua.lua
- lua/neogen/locators/typescript.lua
- lua/neogen/utilities/helpers.lua
- lua/neogen/utilities/nodes.lua
This will be deprecated soon and `vim.treesitter` should be used instead where applicable
Thanks!
> Remove usage of nvim-treesitter utilities

- lua/neogen/configurations/python.lua
- lua/neogen/init.lua
Neogen's Python implementation has a bug for return nodes. Return statements are matched recursively, like so
```lua
{
retrieve = "all",
node_type = "return_statement",
recursive = true,
extract = true,
as = i.Return,
},
```
But when you have a function-within-a-function, this crosses the nested function_definition boundary, even if the outer function has no return.
I couldn't figure out if there's a way to get the `tree` expression to "stop recursing on first function_definition" so, instead of trying to solve it in the tree, I added a clean-up step called `validate_direct_returns`.
I also made some (completely unrelated) clean-up edits to `validate_bare_returns`. If you'd like, I can split that work into a separate branch + PR
https://github.com/danymat/neogen/assets/10103049/a3198b7e-78 …
> Bug fix - Python returns now respect nested functions

- README.md
- lua/neogen/configurations/python.lua
- lua/neogen/init.lua
- tests/neogen/python_google_spec.lua
addresses: https://github.com/danymat/neogen/issues/188
- Adds a section in the README.md on how to run unittests
- Python Exceptions are now grouped by type (previously it would list each duplicate)
- A function with `yield` should never include `Returns:` (it was accidentally doing this because of type-hints)
(From the original issue)
I don't know how to fix that one easily. It's still messed up.
> Fixed Python bugs + added unittests

- lua/neogen/configurations/python.lua
- lua/neogen/init.lua
- tests/neogen/python_google_spec.lua
The `validate_direct_returns` function can set `nodes[i.Return]` to `nil`. When that happens, `validate_bare_returns` fails. This PR fixes that + adds a unittest to make sure it doesn't come back.
> Python - Fixed nested return + yield call

- .github/workflows/test.yml
- lua/neogen/configurations/java.lua
- lua/neogen/configurations/php.lua
- lua/neogen/init.lua
- tests/minimal_init.lua
- tests/neogen/java_javadoc_spec.lua
Fixes #182 
@danymat This is just a stupid copy & paste work - so let me know if I missed something obvious.
If the change is fine it could probably also be added to other languages. Or is there any reason why interfaces should not be documented?
> Issue #182 Support interfaces in Java and PHP

- lua/neogen/configurations/java.lua
- lua/neogen/init.lua
Before:
```java
package com;
public record ExampleRecord(
Integer id
) {
}
```
After:
```java
package com;
/**
* [TODO:description]
*
*/
public record ExampleRecord(
Integer id
) {
}
```
> fix(java): support record annotation in java (#182)

- lua/neogen/init.lua
Update the LuaLS/EmmyLua annotation for the `generate` function to explicitly mark the `opts` parameter as optional. 
This change aligns the documentation with the existing implementation and resolves language server warnings when calling the function without arguments.
> docs: mark `opts` parameter as optional in `generate` function

- README.md
- lua/neogen/init.lua
- lua/neogen/snippet.lua
This PR adds support for newly released [mini.snippets](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-snippets.md) and follows the path of #164. Plus minor documentation tweaks.
> feat: add support for `mini` snippet engine ('mini.snippets')
